name: Publish to NuGet

on:
  #push:
  #  branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
     
    - name: Get Version
      id: get_version
      run: echo "##[set-output name=VERSION;]$(grep -oPm1 "(?<=<Version>)[^<]+" DifySharp/DifySharp.csproj)"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --output ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v${{ steps.get_version.outputs.VERSION }}'
        release_name: 'Release v${{ steps.get_version.outputs.VERSION }}'
        draft: false
        prerelease: false
