name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      KNOWLEDGE_BASE_API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: dotnet test
